[build]
  command = "cd backend && npm install serverless-http"
  publish = "frontend"
  
[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serve"
  status = 200

[[redirects]]
  from = "/*"
  to = "/screening-form.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
