[build]
  command = "cd backend && npm install"
  publish = "frontend"

# Proxy API calls to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true

# Catch-all for frontend routes
[[redirects]]
  from = "/*"
  to = "/screening-form.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
